[package]
name = 'CharacterCards'
version = '1.0.0'

[dependencies]
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
TokenObjects = { local = "../../../aptos-core/aptos-move/move-examples/token_objects" }
TokenObjectsHolder = { local = "../token_objects_holder" }

[addresses]
character_cards = "0xcafe"